-- Create an optimized role enum and association table
create type public.app_role as enum ('student', 'teacher', 'admin');

create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null, -- references auth.users on delete cascade
  role app_role not null,
  unique (user_id, role)
);

create table public.students (
  id uuid primary key default gen_random_uuid(),
  roll_number text not null unique,
  name text not null,
  created_at timestamp with time zone default now()
);

create table public.courses (
  id uuid primary key default gen_random_uuid(),
  course_code text not null unique,
  name text not null,
  faculty_id text not null,
  created_at timestamp with time zone default now()
);

create table public.schedule (
  id uuid primary key default gen_random_uuid(),
  course_code text references public.courses(course_code),
  day text not null,
  time_slot text not null,
  room_number text,
  created_at timestamp with time zone default now()
);

create table public.attendance_logs (
  id uuid primary key default gen_random_uuid(),
  student_id uuid references public.students(id),
  course_code text references public.courses(course_code),
  status text not null,
  timestamp timestamp with time zone default now()
);

-- Indexes
create index idx_students_roll_number on public.students using btree (roll_number);
create index idx_courses_faculty_id on public.courses using btree (faculty_id);
create index idx_schedule_day_time_slot on public.schedule using btree (day, time_slot);
create index idx_attendance_logs_student_course on public.attendance_logs using btree (student_id, course_code);
create index idx_attendance_logs_timestamp on public.attendance_logs using brin (timestamp);
